"""Add nutrition_score

Revision ID: 31c850afc5cb
Revises: 979392ab8b46
Create Date: 2026-03-07 12:18:03.616467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c850afc5cb'
down_revision = '979392ab8b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrition_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_entries', schema=None) as batch_op:
        batch_op.drop_column('nutrition_score')

    # ### end Alembic commands ###
