"""Added BMI columns

Revision ID: 056628a9df4a
Revises: 81237a58cb26
Create Date: 2026-03-11 20:09:56.221303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056628a9df4a'
down_revision = '81237a58cb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_plans', schema=None) as batch_op:
        batch_op.drop_column('diet_plan')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmi_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bmi_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bmi_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bmi_updated_at')
        batch_op.drop_column('bmi_category')
        batch_op.drop_column('bmi_value')

    with op.batch_alter_table('recovery_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_plan', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
