"""Add health_streak and SystemConfig

Revision ID: 979392ab8b46
Revises: 6a84c24763f8
Create Date: 2026-03-07 12:14:37.489342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979392ab8b46'
down_revision = '6a84c24763f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('health_streak')

    # ### end Alembic commands ###
